package kafkaclient

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
}

// Error provides a mock function with given fields: message, data
func (_m *MockLogger) Error(message string, data map[string]interface{}) {
}

// Info provides a mock function with given fields: message, data
func (_m *MockLogger) Info(message string, data map[string]interface{}) {
}
