// Code generated by mockery v1.0.0. DO NOT EDIT.
package kafkaclient

import mock "github.com/stretchr/testify/mock"

// MockCounter is an autogenerated mock type for the Counter type
type MockCounter struct {
	mock.Mock
}

// Inc provides a mock function with given fields: delta, tags
func (_m *MockCounter) Inc(delta int64, tags map[string]string) {
	_m.Called(delta, tags)
}
